### PR TITLE
Start working on forecast endpoint

### PR DESCRIPTION
**Pull request by leiyakenney**
- API calls I think are working
- @joshsherwood1 I'm getting this error: "TypeError: Router.use() requires a middleware function but got a Object" after I added line 23 in my app.js file. I've been getting various versions of this error, and I haven't been able to find anything to fix it; everything I've found online looks like it's an issue of exporting, but I don't have anything to export put in my files yet. Can you take a look and see if you can see what I'm missing?

### CODE REVIEW

**Comment by leiyakenney** [comment]
@joshsherwood1 It looks like creating my forecastRouter got rid of that error (weird, because the last time I tried that it definitely didn't work. Though I redid the whole thing, so I must've had something wonky earlier. HOWEVER, I'm only able to get an error in Postman. I have the api key in the body of my request, and the location as params, per the endpoint. Any ideas?

**Comment by joshsherwood1** [comment]
@leiyakenney i would recommend checking that you have the header content-type: application/json? The request will not work without it. Also, make sure that you have marked the body as JSON in Postman

**Comment by leiyakenney** [comment]
@joshsherwood1 you're absolutely right I didn't have that header condition in there! I did have the body marked as JSON though. Sadly, that didn't fix my problem. I'm hoping it's maybe because I haven't gotten data formatted, seeing as that's an issue I've seen before on this pr. I'm going to go down that route and I'll let you know how it goes. Thanks for the advice!

**Comment by leiyakenney** [comment]
@scottzero this is where I'm running into issues - my newest fun adventure is this "400 Poorly Formatted Request" error. I assume it has to do with my API calls, but I'm honestly not sure where I'm going wrong. Can you take a look?

**Comment by scottzero** [comment]
> @scottzero this is where I'm running into issues - my newest fun adventure is this "400 Poorly Formatted Request" error. I assume it has to do with my API calls, but I'm honestly not sure where I'm going wrong. Can you take a look?

@leiyakenney  Hey Leiya! These errors typically stem from a fetch request url with a syntax error, or coordinates not getting passed into a darksky api fetch call, for example. In your helper file I noticed you are using 'exclude' for the darsky api call, I think the correct syntax might be '?exclude=['something','something'] or very similar. exclude=[blocks], I would look at this to start :)

**Comment by leiyakenney** [comment]
@scottzero @joshsherwood1 thank you both for helping me! I ended up going on a Slack call with @alect47 and it was just that I had forgotten to add the const dotenv at the top of my app.js file (oops). In case you ever run into that same issue :)

**Pull request merged**
